baseurl = "http://beastsofbermuda.com/"
languageCode = "en-us"
title = "Beasts of Bermuda"
theme = "hugo-creative-theme"
googleAnalytics = ""
CanonifyUrls=true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Beasts of Bermuda"
	description = "A game about dinosaurs, survival, and a fully working ecosystem."

	# The path must be relative to the static folder
	favicon = "favicon.ico"
    
    # If there is an announcement, adding a notification will
    # be displayed here.
    #[params.notification]
    #    icon = "fa-steam-square"
    #    html = "<img src='BoB_Banner.png' />"
    [params.kickstarter]
        link = ""


	# Navigation
	[params.navigation]
		brand = "Beasts of Bermuda"

		[params.navigation.links]
            [params.navigation.links.screenshots]
                order = 1
                href = "screenshots/"
                display = "Gallery"
            #[params.navigation.links.about]
            #    order = 2
            #    href = "about/"
            #    display = "About"
            #[params.navigation.links.faq]
            #    order = 3
            #    href = "faq/"
            #    display = "FAQ"
            #[params.navigation.links.services]
            #    order = 4
            #    href = "#services"
            #    display = "Services"
            [params.navigation.links.contact]
                order = 5
                href = "#contact"
                display = "Contact"
			#[params.navigation.links.devs]
			#	order = 6
			#	href = "devs/"
			#	display = "Devs"
                
        [params.navigation.external]
        
            [params.navigation.external.blog]
                order = 1
                href = "http://beastsofbermuda.com/blog"
                display = "Blog"
            [params.navigation.external.wiki]
                order = 2
                href = "http://beastsofbermuda.com/wiki/"
                display = "Wiki"
            [params.navigation.external.discord]
                order = 3
                href = "https://discord.gg/PQ5fPNn"
                display = "Discord"
                
	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Beasts of Bermuda"
		subtitle   = "Hi!  Thanks for visiting our webpage.  We've been fairly quiet lately and our webpage hasn't been updated in a while.  Unfortunately, our Kickstarter last September didn't pass.  Rest assured, however, we have been working on Beasts of Bermuda since then and a lot is being done to build our game up for our Steam release!  While our webpage isn't fully up-to-date, our community Discord is much more current.  It contains most of our relevant news, new screenshots, new videos, and places to discuss our game.  All of us developers regularly post and converse here, and we're often too busy to tend to the webpage.  We encourage you to take a look if you're interested in watching us continue development on our game.  The discord link is https://discord.gg/PQ5fPNn."
		buttonText = "View our (a bit outdated) Wiki!"
        #buttonLink = "#services" - changed to point to About section
		buttonLink = "http://beastsofbermuda.com/wiki/w/Main_Page"

	# About section
	#[params.about]
	#	headline    = "We've got what you need!"
	#	description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
	#	buttonText  = "Get started!"


	# Service section
	[params.services]
		#headline = "About the Game"

        #[[params.services.list]]
        #    icon = "fa-thermometer-quarter"
        #    title = "Survival"
        #    description = "You have to constantly be on the alert and manage your #resources to stay alive."

        #[[params.services.list]]
		#	icon = "fa-group"
		#	title = "Multiplayer"
		#	description = "Run wild with your friends in a pack of velociraptors!"

		#[[params.services.list]]
        #    icon = "fa-paw"
        #    title = "Dual Styles"
        #    description = "Play as a carnivore or herbivore with two radically #different styles of play."

        #[[params.services.list]]
        #    icon = "fa-heart"
        #    title = "Developers who Care"
        #    description = "This game is made by developers who will not let this game #die in Early Access!"

        #[params.services.button]
		#	text = "Find out even more"
		#	link = "about/"

    # Portfolio modals
	#[params.portfolio.modal]
    #    client = "Client"
    #    date = "Date"
    #    category = "Category"
    #    buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Follow Beast of Bermuda through Early Development!"
#
#		[params.aside.button]
#			text = "Join the Community Discord"
#			link = "https://discord.gg/PQ5fPNn"
#			#link = "http://steamcommunity.com/groups/PaleoPlayground"

	# Contact section
	[params.contact]
		headline = "Follow Early Development!"
		description = "Have a question or wish to contribute to the project?"
		# phone = "123-456-6789"
        discord = "https://discord.gg/PQ5fPNn"
		email = "beastsofbermuda@gmail.com"
        kickstarter = "https://www.kickstarter.com/projects/1596433999/beasts-of-bermuda"
        
    # The footer
    [params.footer]
        copyright = 2017

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""