title = "Dev Blog - Paleo Playground"
baseURL = "http://paleo-playground.com/blog/"
languageCode = "en-us"
theme = "hugo-theme-shiori"
author = "Paleo Playground Devs"
CanonifyUrls=true
DisqusShortname="paleo-playground"

[params]
    author_name = "Paleo Playground Devs"
    twitter_username = "PredatoriaED"