title = "Dev Blog - Paleo Playground"
baseURL = "http://paleo-playground.com/blog/"
languageCode = "en-us"
theme = "hugo-theme-shiori"
author = "Matthew Weiss"
CanonifyUrls=true

[params]
    author_name = "Matthew Weiss"
    twitter_username = "PredatoriaED"